### PR TITLE
Jmdewart cryo spi

### PR DESCRIPTION
**Pull request by jmdewart**
For the read command should it be 

write
read

or 2 sequential reads?

read
read

[cryostat_card_interface.docx](https://github.com/slaclab/amc-carrier-core/files/2228853/cryostat_card_interface.docx)

### CODE REVIEW

**Comment by jmdewart** [comment]
We will use this for development on the PIC.   Eventually we will update to have named registers.  Should the 'read' command be a write, read or read, read?  Bit 31 needs to be set on the first transaction.

**Comment by bengineerd** [comment]
I believe you want `read, read`.

There is an assumption build into AxiSpiMaster that data from read commands comes back on the same transaction. Probably we want to provide a generic to handle this case, which is also quite common.

**Comment by ruck314** [comment]
@jmdewart I have added Joe's generic SPI module.  The python script for controlling this module still needs to be written

**Comment by jmdewart** [comment]
I updated the _spiCryo.py module to match the new RtmCryoSpiMaster

**Pull request merged**
