### PR TITLE
Change app types and allow different mps message size for lcls1

### PR DESCRIPTION
**Pull request by slacrherbst**
This PR does the following.

1. Add MPS support for the fast wire scanner.

2. Remove the different link node types and replace with link node and application node types.

3. Allow LCLS1 and LCLS2 modes to generate different size MPS messages.

### CODE REVIEW

**Comment by leosap** [comment]
I think there are typo in logic:
you are defining:
constant APP_MPS_AN_TYPE_C 
 constant APP_MPS_LN_TYPE_C , but you are using only one of them but twice in this statement:
 when APP_MPS_LN_TYPE_C | APP_MPS_LN_TYPE_C =>

**Comment by slacrherbst** [comment]
I fixed the typo. This is ready for merge.

**Comment by ruck314** [comment]
@slacrherbst: Are you ready for me to merge this PR into the pre-release branch?

**Comment by slacrherbst** [comment]
Yes please merge.

**Pull request merged**
